### PR TITLE
Newly-pulled docs shouldn't show up in pusher's pendingDocuments

### LINKED ISSUE #1274: pendingDocumentIDs is incorrect
When syncing database for the first time (just pulling), `pendingDocumentIDs` of push replication contains all documents which were pulled.
`changesCount` is actually 0
When stopping/starting replication `pendingDocumentIDs` are cleaned up.

Also, noticed that `pendingDocumentIDs` sometimes don't clean up properly and some documents are never removed

--------
* Version:   1.2.1
* Client OS: iOS 9.3.1
* Server:    4.1

### PR DESCRIPTION
**Pull request by snej**
When the pusher is notified of a new revision, but decides to ignore it
because it's an 'echo' from a pull replication (or because it's rejected
by the filter), it should advance the checkpoint past that rev's
sequence.

This is a good optimization in general, to prevent the next push from
re-scanning the same revisions, but more importantly it tells
CBLReplication.pendingDocuments that those revisions aren't pending.

To fix this I did have to change the timing at which the pusher adds
revs to its internal _pendingSequences set, because it needs to happen
at the same time that skipped sequences are being handled.

Fixes #1274

### CODE REVIEW

File: Unit-Tests/Replication_Tests.m [hunk 1]
```diff
@@ -606,23 +606,23 @@ - (void) test10_ReplicationCookie {
                                    NSHTTPCookieOriginURL: remoteDbURL,
                                    NSHTTPCookiePath: remoteDbURL.path,
                                    NSHTTPCookieValue: @"logmein",
-                                   NSHTTPCookieExpires: [NSDate dateWithTimeIntervalSinceNow: 10]
+                                   NSHTTPCookieExpires: [NSDate distantFuture]
```
Comment (snej) [inline Unit-Tests/Replication_Tests.m]: Note: Not related to this fix, but I think this will prevent intermittent failures in this unit test. (I got one of those failures just now.)
