### PR TITLE
Fix #1440 attachment revpos after delete and recreate doc

### LINKED ISSUE #1440: Attachments failed to replicate when deleted and recreated
This also fails with Android (1.3.1-30) and .NET (1.3.1-13)

Failing test - https://github.com/couchbaselabs/mobile-testkit/blob/feature/add-multiple-sg-replication-test/testsuites/listener/shared/client_sg/attachments.py#L14-L86

Steps to reproduce:
1. Start continuous replication between LiteServ and Sync Gateway
2. Add a few docs with large attachements to LiteServ
3. Immediately after delete the docs on LiteServ
4. Recreate the docs on LiteServ with the same id and attachment (rev = 3-xxxxx)
5. The recreated attachement docs do not sync to sync gateway

Expected: Recreated attachment docs would sync
Actual: They do not

I am seeing these errors in the logs

```
14:21:50.655‖ WARNING: CBLRestPusher[http://192.168.0.49:4985/db]: _bulk_docs got an error: {
    error = "bad_request";
    id = "large_attach_0";
    reason = "Missing digest in stub attachment \"golden_gate_large.jpg\"";
    status = 400;
} {at __40-[CBLRestPusher uploadBulkDocs:changes:]_block_invoke:402}
14:21:50.655‖ WARNING: CBLRestPusher[http://192.168.0.49:4985/db]: _bulk_docs got an error: {
    error = "bad_request";
    id = "large_attach_1";
    reason = "Missing digest in stub attachment \"golden_gate_large.jpg\"";
    status = 400;
```

---
- Version:   1.3.1-6
- Client OS: Mac OSX
- Server:    Sync Gateway 1.3.1-16

### PR DESCRIPTION
**Pull request by pasin**
* Ported the fix from https://github.com/couchbase/couchbase-lite-net/pull/790.

#1440

### CODE REVIEW

File: Source/CBL_ForestDBStorage.mm [hunk 1]
```diff
@@ -944,27 +944,52 @@ - (CBL_Revision*) addDocID: (NSString*)inDocID
...
-
+    
     __block CBL_Revision* putRev = nil;
     __block CBLDatabaseChange* change = nil;
 
     *outStatus = [self inTransaction: ^CBLStatus {
         NSString* docID = inDocID;
-        C4Slice prevRevIDSlice = revID2slice(inPrevRevID);
+        
+        if (inPrevRevID) { // Check if an existing doc?
```
Comment (snej) [inline Source/CBL_ForestDBStorage.mm]: Also check whether `properties.cbl_attachments != nil` since otherwise there's nothing to do. That allows us to skip loading the doc from the db when there are no attachments.

**Comment by pasin** [comment]
@snej I have fixed per your comment. Please review again. Thanks.
