### PR TITLE
Fixed #1323 : attachment content length = 0 when pushing the document

### LINKED ISSUE #1323: Cannot push encrypted attachments when testing with ToDoLite
The issue happens only when enabling encryption with both SQLCipher and ForestDB storage. 

Log:

```
21:13:19.853‖ Database: ForestDB: Database: beginTransaction
21:13:19.853‖ View: Mapping -4qVgzIKJNo8nKwYlfGrafa rev 2-3122c9dd741f49f56d0c82085a02d230
21:13:19.853‖ Database: ForestDB: DB 0x7fbc8302bc00: added 01 --> 0705401000000000000005400000000000000006260004400fffffffffffff053ff000000000000005401400000000000005000000000000000000 (meta ) (seq 6)

21:13:19.853‖ Database: ForestDB: Database: commit transaction
21:13:19.853‖ View: ... Finished re-indexing (lists) to #4
21:13:19.853‖ Query: Query lists: Returning iterator
21:13:19.853‖ View: Checking indexes of (tasksByDate) for tasksByDate
21:13:19.853‖ Database: ForestDB: Database: beginTransaction
21:13:19.854‖ View: Mapping -4qVgzIKJNo8nKwYlfGrafa rev 2-3122c9dd741f49f56d0c82085a02d230
21:13:19.854‖ View:     emit(["-o7yncD6C5TKkLowUHc7nFQ","2016-06-25T04:13:13.013Z"], doc)
21:13:19.854‖ Database: ForestDB: **** update: realKey = [["-o7yncD6C5TKkLowUHc7nFQ","2016-06-25T04:13:13.013Z"],"-4qVgzIKJNo8nKwYlfGrafa"]
21:13:19.854‖ Database: ForestDB: DB 0x7fbc8304d730: added 070706084b2c5f4933362b342a564443464b5b583e332c493a5000062725262b08252b08272a5625290b26280b26280e2526286200000608294f5a3b614044424a4b2d49445b6045393c512f392f0000 --> 2a (meta 04) (seq 5)

21:13:19.854‖ Database: ForestDB: DB 0x7fbc8304d730: added 01 --> 0705401000000000000005401000000000000006290004400fffffffffffff053ff000000000000005401400000000000005000000000000000000 (meta ) (seq 6)

21:13:19.854‖ Database: ForestDB: Database: commit transaction
21:13:19.854‖ View: ... Finished re-indexing (tasksByDate) to #4
21:13:19.854‖ Query: Query tasksByDate: Returning iterator
21:13:19.855‖ WARNING: Attachment 'image' length mismatch; actually 0, declared 49125 {at -[CBLMultipartWriter addAttachment:]:115}
21:13:19.855‖ Sync: CBLRestPusher[http://localhost:4984/todos]: postProgressChanged (3/4, active=1 (batch=0, net=1), online=1)
21:13:19.856‖ Sync: CBLRestPusher[http://localhost:4984/todos]: Queuing CBLMultipartUploader[PUT http://localhost:4984/todos/-4qVgzIKJNo8nKwYlfGrafa?new_edits=false] (multipart, 0kb)
21:13:19.856‖ Sync: CBLRestPusher[http://localhost:4984/todos]: Starting CBLMultipartUploader[PUT http://localhost:4984/todos/-4qVgzIKJNo8nKwYlfGrafa?new_edits=false]
21:13:19.858‖ WARNING: <CBLMultipartWriter: 0x7fbc8320e1b0>: Error on <__NSCFOutputStream: 0x7fbc831532b0>: (null) {at -[CBLMultiStreamWriter setErrorFrom:]:206}
21:13:19.858‖ WARNING: <CBLMultipartWriter: 0x7fbc8320e1b0> wrote 32768 bytes, but expected length was 628! {at -[CBLMultiStreamWriter stream:handleEvent:]:292}
21:13:19.860‖ CBLMultipartUploader[PUT http://localhost:4984/todos/-4qVgzIKJNo8nKwYlfGrafa?new_edits=false]: Got error NSURLError[-1017, "cannot parse response", <http://localhost:4984/todos/-4qVgzIKJNo8nKwYlfGrafa?new_edits=false>]<--CFCFNetworkError[-1017]
21:13:19.860‖ Sync: CBLRestPusher[http://localhost:4984/todos] Progress: set error = NSURLError[-1017, "cannot parse response", <http://localhost:4984/todos/-4qVgzIKJNo8nKwYlfGrafa?new_edits=false>]<--CFCFNetworkError[-1017]
21:13:19.860‖ Sync: CBLRestPusher[http://localhost:4984/todos]: postProgressChanged (3/4, active=1 (batch=0, net=1), online=1)
21:13:19.860‖ Sync: CBLRestPusher[http://localhost:4984/todos] Progress: 4 / 4
21:13:19.860‖ Sync: CBLRestPusher[http://localhost:4984/todos]: postProgressChanged (4/4, active=1 (batch=0, net=1), online=1)
21:13:19.860‖ Sync: CBLRestPusher[http://localhost:4984/todos] Progress: set active = 0
21:13:19.860‖ Sync: CBLRestPusher[http://localhost:4984/todos]: postProgressChanged (4/4, active=0 (batch=0, net=0), online=1)
21:13:19.860‖ Sync: CBLRestPusher[http://localhost:4984/todos]: Failed to xfer 1 revisions; will retry in 60 sec
21:13:19.865| Query: CBLLiveQuery[lists]: ...async query finished (1 rows, status 200)
21:13:19.865| Query: CBLLiveQuery[tasksByDate]: ...async query finished (1 rows, status 200)
21:13:19.865| Query: CBLLiveQuery[tasksByDate]: ...Rows changed! (now 1)
2016-06-24 21:13:19.865 ToDoLite[33590:7937843] CBLArrayDiff: 0 deleted, 0 replaced, 0 inserted, 0 moved, 1 modified
{  }
21:13:19.870| Sync: CBLReplication[to http://localhost:4984/todos]: active, progress = 3 / 4, err: (null)
21:13:19.870| Sync: CBLReplication[to http://localhost:4984/todos]: idle, progress = 4 / 4, err: NSURLError[-1017, "cannot parse response", <http://localhost:4984/todos/-4qVgzIKJNo8nKwYlfGrafa?new_edits=false>]<--CFCFNetworkError[-1017]
21:13:46.605‖ View: CBL_ForestDBViewStorage[lists]: Closing index
21:13:59.789‖ View: CBL_ForestDBViewStorage[lists]: Closing index
21:14:09.540‖ View: CBL_ForestDBViewStorage[tasksByDate]: Closing index
21:14:19.858‖ Sync: CBLRestPusher[http://localhost:4984/todos] RETRYING, to transfer missed revisions...
21:14:19.858‖ Sync: CBLRestPusher[http://localhost:4984/todos] Progress: set error = (null)
21:14:19.858‖ Sync: CBLRestPusher[http://localhost:4984/todos]: postProgressChanged (4/4, active=0 (batch=0, net=0), online=1)
21:14:19.858‖ Sync: CBLRestPusher[http://localhost:4984/todos] Progress: set active = 1
21:14:19.858‖ Sync: CBLRestPusher[http://localhost:4984/todos]: postProgressChanged (4/4, active=1 (batch=0, net=1), online=1)
21:14:19.858‖ Sync: <CBLRemoteSession: 0x7fbc83014ef0>: GET _session
21:14:19.859| Sync: CBLReplication[to http://localhost:4984/todos]: active, progress = 4 / 4, err: (null)
21:14:19.864‖ Sync: CBLRemoteLogin[http://localhost:4984/todos]: Active session, logged in as '115427112219852'
21:14:19.865‖ Sync: CBLRestPusher[http://localhost:4984/todos]: Successfully logged in!
21:14:19.865‖ Sync: <CBLRemoteSession: 0x7fbc83014ef0>: GET _local/ee685835f1e3779b8b668a0b18e1dcde085cd933
21:14:19.865‖ DEALLOC CBLRemoteLogin[http://localhost:4984/todos]
21:14:19.866‖ Sync: CBLRestPusher[http://localhost:4984/todos]: Replicating from lastSequence=3
21:14:19.866‖ Sync: CBLRestPusher[http://localhost:4984/todos]: Received 1 revs
21:14:19.866‖ Sync: *** CBLRestPusher[http://localhost:4984/todos]: BEGIN processInbox (1 sequences)
21:14:19.866‖ Sync: <CBLRemoteSession: 0x7fbc83014ef0>: POST _revs_diff
21:14:19.866‖ Sync: *** CBLRestPusher[http://localhost:4984/todos]: END processInbox (lastSequence=3)
21:14:19.868‖ WARNING: Attachment 'image' length mismatch; actually 0, declared 49125 {at -[CBLMultipartWriter addAttachment:]:115}
21:14:19.868‖ Sync: CBLRestPusher[http://localhost:4984/todos]: postProgressChanged (4/5, active=1 (batch=0, net=1), online=1)
21:14:19.868‖ Sync: CBLRestPusher[http://localhost:4984/todos]: Queuing CBLMultipartUploader[PUT http://localhost:4984/todos/-4qVgzIKJNo8nKwYlfGrafa?new_edits=false] (multipart, 0kb)
21:14:19.868‖ Sync: CBLRestPusher[http://localhost:4984/todos]: Starting CBLMultipartUploader[PUT http://localhost:4984/todos/-4qVgzIKJNo8nKwYlfGrafa?new_edits=false]
21:14:19.869| Sync: CBLReplication[to http://localhost:4984/todos]: active, progress = 4 / 5, err: (null)
21:14:19.871‖ WARNING: <CBLMultipartWriter: 0x7fbc80e76420>: Error on <__NSCFOutputStream: 0x7fbc80c9b190>: (null) {at -[CBLMultiStreamWriter setErrorFrom:]:206}
21:14:19.871‖ WARNING: <CBLMultipartWriter: 0x7fbc80e76420> wrote 32768 bytes, but expected length was 628! {at -[CBLMultiStreamWriter stream:handleEvent:]:292}
21:14:19.871‖ CBLMultipartUploader[PUT http://localhost:4984/todos/-4qVgzIKJNo8nKwYlfGrafa?new_edits=false]: Got error NSURLError[-1017, "cannot parse response", <http://localhost:4984/todos/-4qVgzIKJNo8nKwYlfGrafa?new_edits=false>]<--CFCFNetworkError[-1017]
21:14:19.871‖ Sync: CBLRestPusher[http://localhost:4984/todos] Progress: set error = NSURLError[-1017, "cannot parse response", <http://localhost:4984/todos/-4qVgzIKJNo8nKwYlfGrafa?new_edits=false>]<--CFCFNetworkError[-1017]
21:14:19.871‖ Sync: CBLRestPusher[http://localhost:4984/todos]: postProgressChanged (4/5, active=1 (batch=0, net=1), online=1)
21:14:19.871‖ Sync: CBLRestPusher[http://localhost:4984/todos] Progress: 5 / 5
21:14:19.871‖ Sync: CBLRestPusher[http://localhost:4984/todos]: postProgressChanged (5/5, active=1 (batch=0, net=1), online=1)
21:14:19.871‖ Sync: CBLRestPusher[http://localhost:4984/todos] Progress: set active = 0
21:14:19.871‖ Sync: CBLRestPusher[http://localhost:4984/todos]: postProgressChanged (5/5, active=0 (batch=0, net=0), online=1)
21:14:19.871‖ Sync: CBLRestPusher[http://localhost:4984/todos]: Failed to xfer 1 revisions; will retry in 60 sec
21:14:19.872| Sync: CBLReplication[to http://localhost:4984/todos]: idle, progress = 5 / 5, err: NSURLError[-1017, "cannot parse response", <http://localhost:4984/todos/-4qVgzIKJNo8nKwYlfGrafa?new_edits=false>]<--CFCFNetworkError[-1017]
```

--------
* Version:   Master (26b665dd8fed26260d6edbb3b877b832f7ae51a6)
* Client OS: 9
* Server:    1.3

### PR DESCRIPTION
**Pull request by pasin**
The issue happens only when the database is encrypted. When the attachment is encrypted, the actual content length cannot be determined when getting the attachment stream.

The fixing is to use the declared length as the content length if the attachment is encrypted.

#1323

### CODE REVIEW

File: Source/CBLMultipartWriter.m [hunk 1]
```diff
@@ -109,10 +109,14 @@ - (CBLStatus) addAttachment: (CBL_Attachment*)attachment {
                                                              andLength: &contentLength];
     if (!contentStream)
         return kCBLStatusAttachmentNotFound;
+    
     uint64_t declaredLength = attachment.possiblyEncodedLength;
-    if (declaredLength != 0 && contentLength != declaredLength)
+    if (attachment.isEncrypted)
```
Comment (snej) [inline Source/CBLMultipartWriter.m]: I think it's better to test for `contentLength==0` instead of encryption. `-getContentStreamDecoded:andLength:` returns a zero length to mean it doesn't know the length; for now that happens because of encryption, but it's possible that there could be other reasons.

**Comment by pasin** [comment]
@snej I fixed the code per your comment. Please re-review when you have time.
