### PR TITLE
Fixed #1967 : Make Document, Dictionary, and Array thread-safe

### LINKED ISSUE #1967: 2.0: Concurrent call b/w Database.getDocument(id) and Document.toMutable() could cause race in StringTable.cc
With https://github.com/couchbase/couchbase-lite-ios/pull/1966 PR, [testConcurrentReadForUpdatesDocs](https://github.com/couchbase/couchbase-lite-ios/blob/feature/20-db-thread-safety/Objective-C/Tests/ConcurrentTest.m#L171-L190) and [testConcurrentUpdateSeperateDocInstances](https://github.com/couchbase/couchbase-lite-ios/blob/feature/20-db-thread-safety/Objective-C/Tests/ConcurrentTest.m#L193-L222) do not pass the ThreadSanitizer test with the same reason.

Basically both tests are trying to create a mutable copy of the same document but different instances.

ThreadSanitizer Log:
```
2017-11-22 16:51:56.338923-0800 xctest[68979:8414783] Writing log to /Users/pasin/Library/Developer/CoreSimulator/Devices/788842C1-DF51-492F-9CF3-AD68E629D84F/data/tmp/CouchbaseLiteTests.c4log
Test Suite 'Selected tests' started at 2017-11-22 16:51:56.370
Test Suite 'CouchbaseLiteTests.xctest' started at 2017-11-22 16:51:56.372
Test Suite 'ConcurrentTest' started at 2017-11-22 16:51:56.373
Test Case '-[ConcurrentTest testConcurrentReadForUpdatesDocs]' started.
2017-11-22 16:51:56.377762-0800 xctest[68979:8414783] CouchbaseLite default log level is Debug and above
==================
WARNING: ThreadSanitizer: data race (pid=68979)
  Write of size 4 at 0x7b6c000003e4 by thread T6 (mutexes: write M1491):
  * #0 fleece::StringTable::find(fleece::slice, unsigned int) const StringTable.cc:58 (CouchbaseLite:x86_64+0x6ea2b8)
    #1 fleece::StringTable::find(fleece::slice) const StringTable.hh:33 (CouchbaseLite:x86_64+0x6ce906)
    #2 fleece::SharedKeys::encode(fleece::slice, int&) const SharedKeys.cc:22 (CouchbaseLite:x86_64+0x6c0093)
    #3 fleece::dictImpl<false>::lookupSharedKey(fleece::slice, fleece::SharedKeys*, int&) const Dict.cc:217 (CouchbaseLite:x86_64+0x6c9720)
    #4 fleece::dictImpl<false>::get(fleece::slice, fleece::SharedKeys*) const Dict.cc:90 (CouchbaseLite:x86_64+0x6c6a5f)
    #5 fleece::Dict::get(fleece::slice, fleece::SharedKeys*) const Dict.cc:286 (CouchbaseLite:x86_64+0x6c67d8)
    #6 FLDict_GetSharedKey Fleece_C_impl.cc:164 (CouchbaseLite:x86_64+0x6b664f)
    #7 fleeceapi::Dict::get(FLSlice, _FLSharedKeys*) const FleeceCpp.hh:403 (CouchbaseLite:x86_64+0x6ddb2)
    #8 fleeceapi::MValue<objc_object* __strong>::toNative(fleeceapi::MValue<objc_object* __strong>*, fleeceapi::MCollection<objc_object* __strong>*, bool&) CBLFleece.mm:70 (CouchbaseLite:x86_64+0x6d81c)
    #9 fleeceapi::MValue<objc_object* __strong>::asNative(fleeceapi::MCollection<objc_object* __strong> const*) const MValue.hh:88 (CouchbaseLite:x86_64+0x6e9b2)
    #10 fleeceapi::MRoot<objc_object* __strong>::asNative() const MRoot.hh:58 (CouchbaseLite:x86_64+0x7875a)
    #11 -[CBLDocument updateDictionary] CBLDocument.mm:127 (CouchbaseLite:x86_64+0x781bd)
    #12 -[CBLDocument setC4Doc:] CBLDocument.mm:146 (CouchbaseLite:x86_64+0x78a50)
    #13 -[CBLDocument initWithDatabase:documentID:mustExist:includeDeleted:error:] CBLDocument.mm:69 (CouchbaseLite:x86_64+0x77409)
    #14 -[CBLDatabase documentWithID:error:] CBLDatabase.mm:655 (CouchbaseLite:x86_64+0x95ba)
    #15 -[CBLDatabase documentWithID:] CBLDatabase.mm:154 (CouchbaseLite:x86_64+0x262a)
    #16 __50-[ConcurrentTest testConcurrentReadForUpdatesDocs]_block_invoke_2 ConcurrentTest.m:185 (CouchbaseLiteTests:x86_64+0x2490cd)
    #17 __57-[ConcurrentTest concurrentRuns:waitUntilDone:withBlock:]_block_invoke ConcurrentTest.m:121 (CouchbaseLiteTests:x86_64+0x24640d)
    #18 __tsan::invoke_and_release_block(void*) <null>:3741136 (libclang_rt.tsan_iossim_dynamic.dylib:x86_64+0x634cb)
    #19 _dispatch_client_callout <null>:3741136 (libdispatch.dylib:x86_64+0x32b4)

  Previous write of size 4 at 0x7b6c000003e4 by thread T1:
  * #0 fleece::StringTable::find(fleece::slice, unsigned int) const StringTable.cc:58 (CouchbaseLite:x86_64+0x6ea2b8)
    #1 fleece::StringTable::find(fleece::slice) const StringTable.hh:33 (CouchbaseLite:x86_64+0x6ce906)
    #2 fleece::SharedKeys::encode(fleece::slice, int&) const SharedKeys.cc:22 (CouchbaseLite:x86_64+0x6c0093)
    #3 fleece::dictImpl<false>::lookupSharedKey(fleece::slice, fleece::SharedKeys*, int&) const Dict.cc:217 (CouchbaseLite:x86_64+0x6c9720)
    #4 fleece::dictImpl<false>::get(fleece::slice, fleece::SharedKeys*) const Dict.cc:90 (CouchbaseLite:x86_64+0x6c6a5f)
    #5 fleece::Dict::get(fleece::slice, fleece::SharedKeys*) const Dict.cc:286 (CouchbaseLite:x86_64+0x6c67d8)
    #6 FLDict_GetSharedKey Fleece_C_impl.cc:164 (CouchbaseLite:x86_64+0x6b664f)
    #7 fleeceapi::Dict::get(FLSlice, _FLSharedKeys*) const FleeceCpp.hh:403 (CouchbaseLite:x86_64+0x6ddb2)
    #8 fleeceapi::MValue<objc_object* __strong>::toNative(fleeceapi::MValue<objc_object* __strong>*, fleeceapi::MCollection<objc_object* __strong>*, bool&) CBLFleece.mm:70 (CouchbaseLite:x86_64+0x6d81c)
    #9 fleeceapi::MValue<objc_object* __strong>::asNative(fleeceapi::MCollection<objc_object* __strong> const*) const MValue.hh:88 (CouchbaseLite:x86_64+0x6e9b2)
    #10 fleeceapi::MRoot<objc_object* __strong>::asNative() const MRoot.hh:58 (CouchbaseLite:x86_64+0x7875a)
    #11 -[CBLDocument updateDictionary] CBLDocument.mm:127 (CouchbaseLite:x86_64+0x781bd)
    #12 -[CBLDocument setC4Doc:] CBLDocument.mm:146 (CouchbaseLite:x86_64+0x78a50)
    #13 -[CBLDocument initWithDatabase:documentID:c4Doc:] CBLDocument.mm:41 (CouchbaseLite:x86_64+0x76e54)
    #14 -[CBLMutableDocument initAsCopyWithDocument:dict:] CBLMutableDocument.mm:83 (CouchbaseLite:x86_64+0x3da96)
    #15 -[CBLDocument mutableCopyWithZone:] CBLDocument.mm:94 (CouchbaseLite:x86_64+0x77a36)
    #16 -[CBLDocument toMutable] CBLDocument.mm:99 (CouchbaseLite:x86_64+0x77ac6)
    #17 __50-[ConcurrentTest testConcurrentReadForUpdatesDocs]_block_invoke_2 ConcurrentTest.m:185 (CouchbaseLiteTests:x86_64+0x24911c)
    #18 __57-[ConcurrentTest concurrentRuns:waitUntilDone:withBlock:]_block_invoke ConcurrentTest.m:121 (CouchbaseLiteTests:x86_64+0x24640d)
    #19 __tsan::invoke_and_release_block(void*) <null>:3741136 (libclang_rt.tsan_iossim_dynamic.dylib:x86_64+0x634cb)
    #20 _dispatch_client_callout <null>:3741136 (libdispatch.dylib:x86_64+0x32b4)

  Issue is caused by frames marked with "*".

  Location is heap block of size 1680 at 0x7b6c00000000 allocated by main thread:
    #0 operator new(unsigned long) <null>:3741152 (libclang_rt.tsan_iossim_dynamic.dylib:x86_64+0x68dee)
    #1 litecore::DataFile::documentKeys() const DataFile.cc:356 (CouchbaseLite:x86_64+0x134ef7)
    #2 litecore::SQLiteDataFile::reopen() SQLiteDataFile.cc:253 (CouchbaseLite:x86_64+0x176b7d)
    #3 litecore::SQLiteDataFile::SQLiteDataFile(litecore::FilePath const&, litecore::DataFile::Options const*) SQLiteDataFile.cc:177 (CouchbaseLite:x86_64+0x1752f8)
    #4 litecore::SQLiteDataFile::SQLiteDataFile(litecore::FilePath const&, litecore::DataFile::Options const*) SQLiteDataFile.cc:176 (CouchbaseLite:x86_64+0x1743d8)
    #5 litecore::SQLiteDataFile::Factory::openFile(litecore::FilePath const&, litecore::DataFile::Options const*) SQLiteDataFile.cc:159 (CouchbaseLite:x86_64+0x174325)
    #6 c4Internal::Database::newDataFile(litecore::FilePath const&, C4DatabaseConfig const&, bool) Database.cc:133 (CouchbaseLite:x86_64+0x3082f2)
    #7 c4Internal::Database::Database(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, C4DatabaseConfig) Database.cc:147 (CouchbaseLite:x86_64+0x308abc)
    #8 c4Database::c4Database(litecore::FilePath const&, C4DatabaseConfig) Database.hh:193 (CouchbaseLite:x86_64+0x1513f2)
    #9 c4Database::c4Database(litecore::FilePath const&, C4DatabaseConfig) Database.hh:193 (CouchbaseLite:x86_64+0x1512dd)
    #10 c4db_open::$_0::operator()() const c4Database.cc:96 (CouchbaseLite:x86_64+0x15112d)
    #11 c4Database* litecore::function_ref<c4Database* ()>::callback_fn<c4db_open::$_0>(long) function_ref.hh:48 (CouchbaseLite:x86_64+0x150fd8)
    #12 litecore::function_ref<c4Database* ()>::operator()() const function_ref.hh:61 (CouchbaseLite:x86_64+0x150ee1)
    #13 c4Database* c4Internal::tryCatch<c4Database*>(C4Error*, litecore::function_ref<c4Database* ()>) c4ExceptionUtils.hh:50 (CouchbaseLite:x86_64+0x14c360)
    #14 c4db_open c4Database.cc:95 (CouchbaseLite:x86_64+0x14c2de)
    #15 -[CBLDatabase open:] CBLDatabase.mm:545 (CouchbaseLite:x86_64+0x901e)
    #16 -[CBLDatabase initWithName:config:error:] CBLDatabase.mm:102 (CouchbaseLite:x86_64+0x17db)
    #17 -[CBLTestCase openDBNamed:error:] CBLTestCase.m:83 (CouchbaseLiteTests:x86_64+0x32904)
    #18 -[CBLTestCase openDB] CBLTestCase.m:90 (CouchbaseLiteTests:x86_64+0x32c96)
    #19 -[CBLTestCase setUp] CBLTestCase.m:43 (CouchbaseLiteTests:x86_64+0x318a0)
    #20 __24-[XCTestCase invokeTest]_block_invoke_3 <null>:3741152 (XCTest:x86_64+0x1a314)

  Mutex M1491 (0x7b1800010c98) created at:
    #0 pthread_mutex_lock <null>:3741024 (libclang_rt.tsan_iossim_dynamic.dylib:x86_64+0x36cde)
    #1 recursive_mutex_tt<false>::lock() <null>:3741024 (libobjc.A.dylib:x86_64+0xf4ba)
    #2 -[ConcurrentTest createAndSaveDocs:error:] ConcurrentTest.m:62 (CouchbaseLiteTests:x86_64+0x244466)
    #3 -[ConcurrentTest testConcurrentReadForUpdatesDocs] ConcurrentTest.m:177 (CouchbaseLiteTests:x86_64+0x248b2c)
    #4 __invoking___ <null>:3741024 (CoreFoundation:x86_64+0x7c49b)

  Thread T6 (tid=8414863, running) is a GCD worker thread

  Thread T1 (tid=8414854, running) is a GCD worker thread

SUMMARY: ThreadSanitizer: data race StringTable.cc:58 in fleece::StringTable::find(fleece::slice, unsigned int) const
```

### PR DESCRIPTION
**Pull request by pasin**
* Made Document, Dictionary, and Array thread-safe. The MutableDocument, MutableDictionary, and MutableArray are not guarantee to be thread-safe.

*  Created a shared lock which could either be the database object or the self object to lock all of the mcollection’s operations.

#1967

### CODE REVIEW

File: Objective-C/CBLArray.mm [hunk 1]
```diff
@@ -281,4 +312,15 @@ - (NSUInteger) hash {
 }
 
 
+#pragma mark - Lock
+
+
+- (NSObject*) sharedLock {
+    CBLDatabase* db = nil;
```
Comment (snej) [inline Objective-C/CBLArray.mm]: Precompute this in the init method and store it in an ivar; it's too expensive to compute on every property access. (Probably needs to be marked as `__weak` to avoid a ref-cycle.)

File: Objective-C/CBLDictionary.mm [hunk 2]
```diff
@@ -264,28 +301,42 @@ - (BOOL) isEqual: (id)object {
...
     }
-    return hash;
+}
+
+
+#pragma mark - Lock
+
+
+- (NSObject*) sharedLock {
+    CBLDatabase* db = nil;
```
Comment (snej) [inline Objective-C/CBLDictionary.mm]: Same comment as in CBLArray: Precompute this in the init method and store it in an ivar; it's too expensive to compute on every property access. (Probably needs to be marked as `__weak` to avoid a ref-cycle.)

File: Objective-C/CBLDictionary.mm [hunk 3]
```diff
@@ -264,28 +301,42 @@ - (BOOL) isEqual: (id)object {
...
-                return NO;
-        } else {
-            if ([other valueForKey: key] || ![other containsValueForKey: key])
-                return NO;
+    CBL_LOCK(self.sharedLock) {
+        for (MDict<id>::iterator i(_dict); i; ++i) {
+            NSString* key = i.nativeKey();
+            id value = i.nativeValue();
+            if (value) {
+                if (![value isEqual: [other valueForKey: key]])
```
Comment (snej) [inline Objective-C/CBLDictionary.mm]: Calling `other` while locked is unsafe; it can deadlock if another thread is calling `isEqual:` on `other`. (Assuming that the sharedLock is `self`, not `db`.)

File: Objective-C/CBLDocument.mm [hunk 4]
```diff
@@ -135,12 +135,14 @@ - (BOOL) isEmpty {
...
-        _dict = _root->asNative();
+        CBL_LOCK(_database) {
+            _dict = _root->asNative();
+        }
     } else {
         // New document:
         _root.reset();
         _dict = self.isMutable ? (id)[[CBLNewDictionary alloc] init]
-                               : [[CBLDictionary alloc] initEmpty];
+        : [[CBLDictionary alloc] initEmpty];
```
Comment (snej) [inline Objective-C/CBLDocument.mm]: fix indentation

**Comment by snej** [comment]
-[CBLArray objectAtIndexedSubscript:] accesses `_array` so it needs locking too.

**Comment by pasin** [comment]
@snej Thanks for the review. I updated the PR. Could you please re-review? Thanks!

File: Objective-C/CBLArray.mm [hunk 5]
```diff
@@ -59,21 +66,33 @@ - (instancetype) initWithCopyOfMArray: (const MArray<id>&)mArray
     self = [super init];
     if (self) {
         _array.initAsCopyOf(mArray, isMutable);
+        _sharedLock = [self _sharedLock];
     }
     return self;
 }
 
 
+- (NSObject*) _sharedLock {
```
Comment (snej) [inline Objective-C/CBLArray.mm]: Since this is only called from the init methods, it seems more like an init method itself. Why not make it `-init`, and call it as `[self init]` at the start of the other initializers?

File: Objective-C/CBLArray.mm [hunk 6]
```diff
@@ -59,21 +66,33 @@ - (instancetype) initWithCopyOfMArray: (const MArray<id>&)mArray
...
+
+
 - (id) copyWithZone:(NSZone *)zone {
     return self;
 }
 
 
 - (CBLMutableArray*) mutableCopyWithZone:(NSZone *)zone {
-    return [[CBLMutableArray alloc] initWithCopyOfMArray: _array isMutable: true];
+    CBL_LOCK(self.sharedLock) {
```
Comment (snej) [inline Objective-C/CBLArray.mm]: Better to do `CBL_LOCK(_sharedLock)`, here and below. I know I'm being obsessive about performance, but these accessors are important and it's best to add a little overhead as possible.

File: Objective-C/CBLDictionary.mm [hunk 7]
```diff
@@ -65,21 +71,33 @@ - (instancetype) initWithCopyOfMDict: (const MDict<id>&)mDict
     self = [super init];
     if (self) {
         _dict.initAsCopyOf(mDict, isMutable);
+        _sharedLock = [self _sharedLock];
     }
     return self;
 }
 
 
+- (NSObject*) _sharedLock {
```
Comment (snej) [inline Objective-C/CBLDictionary.mm]: Same comment here as in CBLArray.mm.

File: Objective-C/CBLDictionary.mm [hunk 8]
```diff
@@ -301,17 +316,19 @@ - (BOOL) isEqual: (id)object {
...
-            NSString* key = i.nativeKey();
-            id value = i.nativeValue();
-            if (value) {
-                if (![value isEqual: [other valueForKey: key]])
-                    return NO;
-            } else {
-                if ([other valueForKey: key] || ![other containsValueForKey: key])
-                    return NO;
-            }
+    for (MDict<id>::iterator i(_dict); i; ++i) {
```
Comment (snej) [inline Objective-C/CBLDictionary.mm]: Unsynchronized access to `_dict` here.

**Comment by pasin** [comment]
I fixed the PR. Could you please re-review? Thanks!
